gitlabUrl: "https://gitlab.bluraya.shop"

# rbac for gitlabrunner main
rbac:
  create: true
  clusterWideAccess: true #for creating pods
 
serviceAccount:
  create: true
  name: "my-runner-gitlab-runner"

runners:
  privileged: true
  secret: "gitlab-runner-secret"
  # for the new pods runner
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:22.04"
        privileged = true 
        service_account = "my-runner-gitlab-runner" 