image: docker:20.10.16

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  # משתנה אוטומטי של גיטלאב שמרכיב את שם ה-Image והתגית (Commit SHA)
  IMAGE_TAG: "infinity-app-alb-167884405.eu-central-1.elb.amazonaws.com:5050/bluraya55/infinity-home-assignment:$CI_COMMIT_SHORT_SHA" 

services:
  - name: docker:20.10.16-dind
    # שורה קריטית: כופה על הדיימון לרוץ בלי הצפנה כדי שיתאים ל-2375
    command: ["--tls=false", "--insecure-registry=infinity-app-alb-167884405.eu-central-1.elb.amazonaws.com:5050"]

stages:
  - build, test and push
  - deploy

build_image:
  stage: build, test and push
  script:
    - cd app

    # build
    - echo "Building Docker image..."
    - docker build -t $IMAGE_TAG .
    
    # test
    - echo "Running container in background for testing..."
    - docker run -d --name test-app -p 3000:3000 $IMAGE_TAG
    - sleep 5 # נותן ל-Node.js שנייה לעלות
    - apk add --no-cache curl
    - echo "Testing with curl..."
    - curl -f http://localhost:3000/health || exit 1
    - docker rm -f test-app

    # push
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Pushing image to GitLab Container Registry..."
    - docker push $IMAGE_TAG

deploy_to_eks:
  stage: deploy
  # Image שמכיל בתוכו כבר את Helm ו-kubectl
  image: dtzar/helm-kubectl:3.12 
  script:
    - cd app
    - apk add --no-cache jq curl
    
    # 1. משיכת הסוד מ-Vault (Authentication & Authorization)
    - echo "Fetching secret from Vault..."
    - echo "Trying to reach Vault at $VAULT_ADDR"
    - >
      SECRET_JSON=$(curl -sS -H "X-Vault-Token: $VAULT_CI_TOKEN" $VAULT_ADDR/v1/secret/data/myapp)
    - echo "Vault response length is ${#SECRET_JSON} characters"
    #- >
    #  SECRET_JSON=$(curl -s -H "X-Vault-Token: $VAULT_CI_TOKEN" $VAULT_ADDR/v1/secret/data/myapp)
    - SECRET_WORD=$(echo $SECRET_JSON | jq -r '.data.data.Assignment')
    - echo "Secret retrieved successfully!"

    # 2. פריסה לקלאסטר עם Helm והזרקת הסוד
    - echo "Deploying to EKS..."
    - >
      helm upgrade --install infinity-app ./chart
      --set image.repository=$CI_REGISTRY_IMAGE
      --set image.tag=$CI_COMMIT_SHORT_SHA
      --set secretWord="$SECRET_WORD"