services:

  gitlab:

    image: gitlab/gitlab-ce:latest

    container_name: gitlab

    restart: always

    hostname: 'gitlab.bluraya.shop'

    environment:

      GITLAB_OMNIBUS_CONFIG: |
      
        external_url 'https://gitlab.bluraya.shop' # תחזיר ל-https
        registry_external_url 'https://registry.bluraya.shop'
        
        # השורות הקריטיות שמונעות את הלופ:
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 5050
        
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

    ports:

      - '80:80'

      - '443:443'

      - '2222:22'

      - '5050:5050'

    volumes:

      - '/srv/gitlab/config:/etc/gitlab'

      - '/srv/gitlab/logs:/var/log/gitlab'

      - '/srv/gitlab/data:/var/opt/gitlab'

    shm_size: '256m'
