---
- name: create vault directory
  file:
    path: /opt/vault
    state: directory
    owner: ubuntu
    group: ubuntu

- name: copy vault docker-compose file
  copy:
    src: docker-compose.yml
    dest: /opt/vault/docker-compose.yml

- name: start vault with docker compose
  command: docker compose up -d --remove-orphans
  args:
    chdir: /opt/vault
  #become_user: ubuntu