[gitlab]
i-02b9e8abe0ae8d691

[vault]
i-02c485a0a372c5e27

[all:vars]
ansible_connection=aws_ssm
ansible_aws_ssm_region=eu-central-1
ansible_user=ubuntu
ansible_aws_ssm_bucket_name=infinity-ansible-ssm-20260419084520938700000005