---
- name: setup docker on all servers
  hosts: all
  become: yes
  roles:
    - docker

- name: deploy gl
  hosts: gitlab
  become: yes
  roles:
    - gitlab

- name: deploy Vault
  hosts: vault
  become: yes
  roles:
    - vault