apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  annotations:
    # use my acm
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:986449364495:certificate/fca7c7aa-7078-4fb0-a349-34e6511545c6"
    # listenr for 443
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # rederect 80 -> 443
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: https
      port: 443
      targetPort: 3000
    - name: http
      port: 80
      targetPort: 3000