---
- name: create gitlabitLab directory
  file:
    path: /opt/gitlab
    state: directory
    owner: ubuntu
    group: ubuntu

- name: copy gl docker-compose file
  copy:
    src: docker-compose.yml
    dest: /opt/gitlab/docker-compose.yml

- name: start gl via docker compose
  command: docker compose up -d --remove-orphans
  args:
    chdir: /opt/gitlab
  #become_user: ubuntu